# Generated by Django 5.2.15 on 2026-08-18 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ondray', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingdocument',
            name='checksum',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
